language: 'en'
servername: 'this server'
messageformat: '[[](gray)[OnlineTime](dark_aqua)[]](gray) %message%'
saveinterval: 30
mysql:
 enabled: false
 host: 127.0.0.1
 port: 3306
 database: minecraft_database
 username: minecraft_user
 password: password
 