language: 'en' # for available languages see / edit messages.yml
servername: 'this server'
messageformat: '&gray&\[[OnlineTime](dark_aqua)\] %message%' # See https://github.com/Phoenix616/MineDown#syntax
saveinterval: 30 # seconds
storage: 'yaml' # to use e.g. mysql set to 'database' and configure database.properties
