language: 'en'
servername: 'this server'
messageformat: '[[](gray)[OnlineTime](dark_aqua)[]](gray) %message%'
saveinterval: 30
mysql:
 enabled: false
 host: localhost
 port: 3306
 database: db
 username: username
 password: password
 import: true